repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: run isort
        types: [python]

      - id: black
        name: black
        stages: [commit]
        language: system
        entry: run black
        types: [python]

      - id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: run flake8
        types: [python]
        exclude: setup.py

      - id: mypy
        name: mypy
        stages: [commit]
        language: system
        entry: run mypy
        types: [python]
        pass_filenames: false

      - id: pytest
        name: pytest
        stages: [commit]
        language: system
        entry: run pytest
        types: [python]

      - id: pytest-cov
        name: pytest
        stages: [push]
        language: system
        entry: run pytest --cov --cov-fail-under=100
        types: [python]
        pass_filenames: false